GET http://localhost:8080/JspWebApp/api/v1/product/26/id

###

PUT http://localhost:8080/JspWebApp/api/v1/product/new
Content-Type: application/json

{
  "description": "REST product",
  "name": "REST product",
  "price": 199.00
}

###

GET http://localhost:8080/JspWebApp/api/v1/product/all

###

DELETE http://localhost:8080/JspWebApp/api/v1/product/26/id